#spring:
#  application:
#    name: hello-spring-cloud-web-admin-ribbon
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#
#server:
#  port: 8764
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-ribbon
      label: master
      profile: dev