#spring:
#  application:
#    name: hello-spring-cloud-zuul
#boot:
#  admin:
#    client:
#      url: http://localhost:8084
#server:
#  port: 8769
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#zuul:
#  routes:
#    api-a:
#      path: /api/a/**
#      serviceId: hello-spring-cloud-web-admin-ribbon
#    api-b:
#      path: /api/b/**
#      serviceId: hello-spring-cloud-web-admin-feign
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-zuul
      label: master
      profile: dev