spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/juno4717/hello-spring-cloud
          search-paths: spring-cloud-config
          username: juno4717
          password: 0321123qQ
          skip-ssl-validation: true
zipkin:
  base-url: http://localhost:9411
server:
  port: 8888
boot:
  admin:
    client:
      url: http://localhost:8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/